@startuml
top to bottom direction

interface InterfaceArchivo {
    +prettyPrint(): String
    +get...(): ...
}

together {
    class FileOO2 implements InterfaceArchivo{
        -nombre: String
        -extension: String
        -tamanio: Integer
        -creacion: Date
        -modificacion: Date
        -permisos: String
        +<<create>> FileOO2(...)
        +get...(): ...
    }

    abstract class ArchivoDecorador implements InterfaceArchivo {
        +<<create>> ArchivoDecorador(a: InterfaceArchivo)
        +get...(): ...
    }
}

together {
    class NombreDecorador extends ArchivoDecorador {
        +<<create>> NombreDecorador(...)
        +prettyPrint(): String
    }
    class ExtensionDecorador extends ArchivoDecorador {
        +<<create>> ExtensionDecorador(...)
        +prettyPrint(): String
    }
    class TamanioDecorador extends ArchivoDecorador {
        +<<create>> TamanioDecorador(...)
        +prettyPrint(): String
    }
    class CreacionDecorador extends ArchivoDecorador {
        +<<create>> CreacionDecorador(...)
        +prettyPrint(): String
    }
    class ModificacionDecorador extends ArchivoDecorador {
        +<<create>> ModificacionDecorador(...)
        +prettyPrint(): String
    }
    class PermisosDecorador extends ArchivoDecorador {
        +<<create>> PermisosDecorador(...)
        +prettyPrint(): String
    }
}



ArchivoDecorador --> InterfaceArchivo

@enduml