@startuml
abstract class Prenda<<Componente>>{
    +getValorPrendario(): Real
    +<<abstract>>getValor(): Real
    #<<abstract>>getLiquidez(): Real
}

class Automovil<<Hoja>> extends Prenda{
    -modelo: Integer
    -kilometraje: Real
    -costo0km: Real
    +<<create>> Automovil(m: Integer; k: Real; c: Real)
    +getValor(): Real
    #getLiquidez(): Real
}

class Inmueble<<Hoja>> extends Prenda{
    -direccion: String
    -superficie: Real
    -costom2: Real
    +<<create>> Inmueble(d: String; s: Real; c: Real)
    +getValor(): Real
    #getLiquidez(): Real
}

class Alquiler<<Hoja>> extends Prenda{
    -comienzoContrato: Date
    -finContrato: Date
    -costoMensual: Real
    +<<create>> Alquiler(c: Date; f: Date; cm: Real)
    +getValor(): Real
    #getLiquidez(): Real
}

class Combinado<<Compuesto>> extends Prenda{
    +getValor(): Real
    #getLiquidez(): Real
}

Combinado -->"*" Prenda
@enduml